trigger:
  branches:
    include:
      - main
  tags:
    exclude:
      - '*'

pr:
  - main

variables:
  dotnetSdkVersion: '8.x'
  buildConfiguration: 'Release'
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: |
    {
      "endpointCredentials": [
        {
          "endpoint": "https://pkgs.dev.azure.com/RM361756/_packaging/My_Packages/nuget/v3/index.json",
          "username": "az",
          "password": "$(NUGET_PAT)"
        }
      ]
    }

pool:
  name: 'Default'

stages:
  - stage: Build
    displayName: '1. Build Project'
    jobs:
      - job: 'BuildJob'
        displayName: 'Build'
        steps:
          - task: UseDotNet@2
            displayName: 'Setup .NET 8'
            inputs:
              packageType: sdk
              version: '$(dotnetSdkVersion)'
          
          - script: dotnet restore FCG-User-API.sln
            displayName: 'Restore dependencies'
            env:
              NUGET_PAT: $(NUGET_PAT)

          - task: DotNetCoreCLI@2
            displayName: 'Build project'
            inputs:
              command: build
              projects: '**/*.sln'
              arguments: '--configuration $(buildConfiguration) --no-restore'

  - stage: Test
    displayName: '2. Run Unit Tests'
    dependsOn: Build
    jobs:
    - job: TestJob
      displayName: Execute Unit Tests
      steps:
        - task: UseDotNet@2
          displayName: 'Setup .NET 8'
          inputs:
            packageType: sdk
            version: '$(dotnetSdkVersion)'

        - task: DotNetCoreCLI@2
          displayName: 'Run unit tests'
          inputs:
            command: test
            projects: 'tests/FCG_Users.Tests/FCG_Users.Tests.csproj'
            arguments: '--configuration $(buildConfiguration) --settings coverlat.runsettings --collect "XPlat Code Coverage"'
